alias: System Change Theme
trigger:
  - platform: state
    entity_id: input_select.system_day_state
  - platform: homeassistant
    event: start
action:
  - service: frontend.set_theme
    data_template:
      name: >
        {%- if states.input_select.system_day_state.state in ["Evening", "Bedtime", "Night"] -%}
          Google Dark Theme
        {%- else -%}
          Google Light Theme
        {%- endif -%}
