alias: System Day State Changer
trigger:
  - platform: sun
    event: sunrise
  - platform: time
    at: '12:00:00'
  - platform: sun
    event: sunset
  - platform: time
    at: '23:00:00'
  - platform: time 
    at: '00:00:00'
action:
  - service: input_select.select_next
    entity_id: input_select.system_day_state
