alias: System Bring Back Tasmotas
trigger:
  - platform: homeassistant
    event: start
action:
  - delay: '00:00:30'
  - service: mqtt.publish
    data:
      payload: "SetOption19 1; Delay 100; State"
      topic: tasmotas/cmnd/backlog
      retain: true
