language: python

python: "3.6.4"

before_install:
  - touch fakekey.pem
  - mv homeassistant/fake_secrets.yaml homeassistant/secrets.yaml

install: pip3 install homeassistant

jobs:
  include:
    - stage: test
      script: hass -c homeassistant/ --script check_config --info all
    - stage: test
      script: hass -c homeassistant_rpi_rf_instance/ --script check_config --info all