homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

http:
  api_password: !secret apipass
  ssl_certificate: !secret ssl_certif
  ssl_key: !secret ssl_key
  base_url: !secret base_url

updater:
  include_used_components: true

frontend:

config:

discovery:

history:

logbook:

map:

sun:

tts:
  - platform: google

mqtt:
  broker: 127.0.0.1
  username: homeassistant
  password: !secret mqttpass

ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

weather:
  - platform: darksky
    api_key: !secret darkskyapikey

mqtt_eventstream:
  publish_topic: homeassistant/master/events

panel_iframe:
  motion:
    title: Motion
    url: 'http://192.168.0.89:8765/'
    icon: mdi:camera

alarm_control_panel:
  - platform: manual
    name: Test Alarm
    code: !secret alarm_code
    delay_time: 5
    pending_time: 5

notify:
  - platform: html5
    name: Html5 Notifier
    gcm_api_key: !secret gcm_server_key
    gcm_sender_id: !secret gcm_sender_id

google: !include includes/google.yaml
cast: !include includes/cast.yaml
device_tracker: !include includes/nmap_scanner.yaml
binary_sensor: !include_dir_merge_list includes/binary_sensor
sensor: !include_dir_merge_list includes/sensor
media_player: !include_dir_merge_list includes/media_players
automation: !include_dir_merge_list includes/automations/
scene: !include_dir_merge_list includes/scenes/
switch: !include_dir_merge_list includes/switches/
light: !include_dir_merge_list includes/light/
camera: !include_dir_merge_list includes/camera
google_assistant: !include includes/google_assistant.yaml
input_boolean: !include includes/input_boolean.yaml
script: !include_dir_named includes/scripts


