homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

http:
  api_password: !secret apipass
  ssl_certificate: !secret ssl_certif
  ssl_key: !secret ssl_key
  base_url: !secret base_url

frontend:

config:

updater:
  include_used_components: true

discovery:

history:

logbook:

map:

sun:

tts:
  - platform: google

mqtt:
  broker: 127.0.0.1
  username: homeassistant
  password: !secret mqttpass

ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

weather:
  - platform: darksky
    api_key: !secret darkskyapikey

google: !include includes/google.yaml

device_tracker: !include includes/nmap_scanner.yaml

sensor: !include_dir_merge_list includes/sensor
media_player: !include_dir_merge_list includes/media_players
automation: !include_dir_merge_list includes/automations/
scene: !include_dir_merge_list includes/scenes/
switch: !include_dir_merge_list includes/switches/
light: !include_dir_merge_list includes/light/
camera: !include_dir_merge_list includes/camera
google_assistant: !include includes/google_assistant.yaml
feedreader: !include includes/feedreader.yaml
input_boolean: !include includes/input_boolean.yaml

script: !include_dir_named includes/scripts

shell_command:
  lovelace_gen: '/home/homeassistant/.homeassistant/lovelage-gen.py'
