title: Home
views: 
        - title: Bedroom
          id: bedroom
          icon: mdi:hotel
          badges:
                - sensor.bedroom_humidity
                - sensor.bedroom_temperature
          
          cards:
                - type: entities
                  title: Lights
                  entities:
                        - switch.bedroom_light
                        - switch.bedside_lamp
                        - switch.desk_lamp
                        - light.bed_light_strip
          
                - type: entities 
                  title: Plugs
                  entities:
                        - switch.generic_door_plug
                   
                - type: picture-entity
                  entity: camera.bedroom_camera
                  show_state: false
        
        - title: Media
          icon: mdi:music
          id: media
          cards:
                - type: entities
                  title: Movie Mode
                  entities: 
                        - input_boolean.bedroom_movie_mode
               
                - type: media-control
                  entity: media_player.bedroom
                
                - type: media-control
                  entity: media_player.kodi_mac_mini
                


        - title: Outside
          icon: mdi:tree
          id: outside
          badges:
                - sensor.air_quality
          cards:
                
                - type: weather-forecast
                  title: Weather
                  entity: weather.dark_sky
                
                - type: entities
                  title: Air Quality
                  entities:
                        - sensor.waqi_grande_torino_leini_piemonte_italy
                        - sensor.waqi_lingotto_torino_piemonte_italy
                        - sensor.waqi_rebaudengo_torino_piemonte_italy
                        - sensor.waqi_rubino_torino_piemonte_italy 
                
                - type: iframe
                  url: https://embed.windy.com/embed2.html
                  aspect_ratio: 100%
        



        - title: Management 
          icon: mdi:gauge
          id: management
          cards:
                
                - type: entity-filter
                  entities:
                      - device_tracker.eliseo
                      - device_tracker.daniele
                      - device_tracker.furkan
                  state_filter:
                      - home
                  card:
                      title: "Who's Home"
                      type: glance
                      show_name: false
                      show_state: false
                
                - type: entities
                  title: Who Cleans?
                  entities: 
                        - sensor.who_cleans     
                
                - type: history-graph
                  title: Speedtest
                  entities:
                        - sensor.speedtest_download
                        - sensor.speedtest_ping
                        - sensor.speedtest_upload
