title: Home
views: 
        - title: Bedroom
          id: bedroom
          badges:
                - sensor.bedroom_humidity
                - sensor.bedroom_temperature
          cards:
                - type: entities
                  title: Lights
                  entities:
                        - switch.bedroom_light
                        - switch.bedside_lamp
                        - switch.desk_lamp
                        - light.bed_light_strip
                - type: entities 
                  title: Plugs
                  entities:
                        - switch.generic_door_plug
                - type: media-control
                  entity: media_player.bedroom
                - type: picture-entity
                  entity: camera.bedroom_camera
                  show_state: false
        - title: Outside
          cards:
                - type: weather-forecast
                  title: Weather
                  entity: weather.dark_sky
                - type: entities
                  title: Air Quality
                  entities:
                        - sensor.waqi_grande_torino_leini_piemonte_italy
                        - sensor.waqi_lingotto_torino_piemonte_italy
                        - sensor.waqi_rebaudengo_torino_piemonte_italy
                        - sensor.waqi_rubino_torino_piemonte_italy 
                - type: iframe
                  url: https://embed.windy.com/embed2.html
                  aspect_ratio: 100%
        
        - title: Management 
          cards:
                - type: conditional
                  conditions: 
                        - entity: group.all_devices
                          state: home
                  card:
                        type: entity-filter
                        entities:
                                - device_tracker.eliseo
                                - device_tracker.furkan
                        state_filter:
                                - home
                        card:
                                title: "Who's Home"
                                type: glance
                                show_name: false
                                show_state: false
                - type: entities
                  title: Who Cleans?
                  entities: 
                        - sensor.who_cleans     
                - type: entities
                  title: Speedtest
                  entities:
                        - sensor.speedtest_download
                        - sensor.speedtest_ping
                        - sensor.speedtest_upload
