alias: Bedroom Motion Lights
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_panel_motion_active
    to: 'on'
condition:
  - condition: template
    value_template: >
      {{ as_timestamp(now()) - as_timestamp(state_attr("automation.bedroom_motion_lights", "last_triggered")) | int > 180 }}
  - condition: state
    entity_id: input_boolean.bedroom_movie_lights
    state: 'off'
action:
  - service: light.turn_on
    data_template:
      entity_id: >
        {% if states.input_select.home_day_state.state in ["Morning", "Afternoon", "Evening"] %}
          light.bedroom_ceiling
        {% else %}
          light.bedroom_accent_bed
        {% endif %}
      rgb_color: [0, 190, 255]

