alias: Bedroom Ceiling Motion
trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_panel_motion_active
    to: 'on'
condition:
  - condition: template
    value_template: >
      {{ states.input_select.home_day_state.state in ["Morning", "Afternoon", "Evening"] }}
  - condition: template
    value_template: >
        {{ as_timestamp(now()) - as_timestamp(state_attr("automation.bedroom_ceiling_motion", "last_triggered")) > 180 }}
  - condition: state
    entity_id: input_boolean.bedroom_movie_lights
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.bedroom_ceiling
