homeassistant:
  time_zone: Europe/Rome
  unit_system: metric
  auth_providers:
    - type: legacy_api_password
      api_password: !secret apipass

sensor: !include_dir_merge_list includes/sensor
switch: !include_dir_merge_list includes/switches/
light: !include_dir_merge_list includes/light/

api:
websocket_api:

