homeassistant:
  time_zone: Europe/Rome
  unit_system: metric

homekit:
  filter:
    include_entities:
      - light.bedroom_desk 
      - light.bedroom_bedside 
      - light.bedroom_ceiling 
      - switch.bedroom_plug
      - light.bedroom_accent_bed 
      - light.bedroom_accent_monitor
      - light.bedroom_accent
      - sensor.bedroom_temperature

switch:
light:

remote_homeassistant:
  instances:
    - host: 192.168.0.1
      access_token: !secret access_token
