homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: metric
  time_zone: Europe/Rome
  
  packages: !include_dir_named components/packages
