title: Home
resources: !include_dir_list lovelace/resources
decluttering_templates: !include_dir_merge_named lovelace/decluttering_templates
custom_header: !include lovelace/custom_header.yaml
views: !include_dir_merge_list lovelace/views
