title: Home
resources:
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
decluttering_templates:
  mini_graph:
    card:
      type: custom:mini-graph-card
      entities:
        - '[[entity_id]]'
      line_color: '[[color]]'
      line_width: 8
      font_size: 75
      animate: true
      name: "[[name]]"
      align_icon: left
      align_header: left
  hk_button:
    default:
      - aspect_ratio: "1/1"
    card:
      type: custom:button-card
      entity: '[[entity_id]]'
      name: "[[name]]"
      show_state: true
      aspect_ratio: "[[aspect_ratio]]"
      hold_action:
        action: more-info
      styles:
        grid:
          - grid-template-areas: '"i" "n" "s"'
          - grid-template-columns: 1fr
          - grid-template-rows: 1fr min-content min-content
        img_cell:
          - align-self: start
          - text-align: start
          - margin-right: calc(66% - 16px)
        name:
          - justify-self: start
          - padding-left: 10px
          - font-weight: bold
        state:
          - justify-self: start
          - padding-left: 10px
        icon: 
          - color: var(--button-card-light-color)
      state:
        - value: 'off'
          styles:
            card:
              - filter: opacity(50%)
            icon:
              - filter: grayscale(100%)
  hk_trigger:
    card:
      type: custom:button-card
      entity: '[[entity_id]]'
      name: "[[name]]"
      show_icon: false
      aspect_ratio: 2/1
      tap_action:
        action: call-service
        service: scene.turn_on
        service_data:
          entity_id: entity


custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

views:
    # View tab title.
  - title: Home
    icon: mdi:home
    cards:
      # First Card 
      - type: custom:simple-weather-card
        entity: weather.home
        name: " "
        backdrop: true
      - type: horizontal-stack
        cards:
          - type: custom:decluttering-card
            template: mini_graph
            variables:
              - entity_id: sensor.bedroom_humidity
              - color: purple
              - name: Humidity
          - type: custom:decluttering-card
            template: mini_graph
            variables:
              - entity_id: sensor.bedroom_temperature
              - color: red
              - name: Temperature
      
      - type: vertical-stack
        title: Lights
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:decluttering-card
                template: "hk_button"
                variables:
                  - entity_id: light.bedroom_ceiling
                  - name: "Ceiling"
              - type: custom:decluttering-card
                template: "hk_button"
                variables:
                  - entity_id: light.bedroom_desk
                  - name: "Desk"
              - type: custom:decluttering-card
                template: "hk_button"
                variables:
                  - entity_id: light.bedroom_bedside
                  - name: "Bedside"
          - type: horizontal-stack
            cards:
              - type: custom:decluttering-card
                template: "hk_button"
                variables:
                  - entity_id: light.bedroom_accent_monitor
                  - name: "Monitor"
              - type: custom:decluttering-card
                template: "hk_button"
                variables:
                  - entity_id: light.bedroom_accent_bed
                  - name: "Bed"
              - type: custom:decluttering-card
                template: "hk_button"
                variables:
                  - entity_id: binary_sensor.bedroom_panel_motion_active
                  - name: "Motion"
 
      - type: entities
        entities:
          - type: "custom:button-entity-row"
            buttons:
              - input_boolean.bedroom_sync_music_with_lights
              - input_boolean.bedroom_movie_lights
          - switch.bedroom_plug
          - person.eliseo_martelli
          - binary_sensor.home_asleep
      - type: vertical-stack
        title: Media
        cards:
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
            shortcuts:
              buttons:
                - name: Warm Piano
                  type: script
                  id: script.bedroom_speaker_play_warm_piano
                - name: Lo-Fi Music
                  type: script
                  id: script.bedroom_speaker_play_lofi
      - type: custom:mini-media-player
        entity: media_player.bedroom_jellyfin
      - type: horizontal-stack
        title: Scenes
        cards:
          - type: custom:decluttering-card
            template: "hk_trigger"
            variables:
              - entity_id: scene.bedroom_warm
              - name: "Warm"
          - type: custom:decluttering-card
            template: "hk_trigger"
            variables:
              - entity_id: scene.bedroom_sea
              - name: "Sea"
          - type: custom:decluttering-card
            template: "hk_trigger"
            variables:
              - entity_id: scene.bedroom_cotton_candy
              - name: "Candy"

  - title: Settings
    icon: mdi:settings
    cards:
      - type: custom:auto-entities
        card:
          title: Automations
          type: entities
        filter:
          include:
            - entity_id: automation.*

      - type: custom:auto-entities
        card:
          title: Printer
          type: entities
        filter:
          include:
            - entity_id: sensor.bedroom_printer_*
      - type: entities
        entities:
          - input_select.home_day_state
