- alias: Mirror Air Freshner Calendar ON
  trigger:
    - platform: state
      entity_id: calendar.airfreshnerschedule
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.generic_door_plug

- alias: Mirror Air Freshner Calendar OFF
  trigger:
    - platform: state
      entity_id: calendar.airfreshnerschedule
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.generic_door_plug
