- alias: Alarm
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.test_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.test_alarm

- alias: Alarm triggered response
  trigger:
    - platform: state
      entity_id: alarm_control_panel.test_alarm
      to: 'triggered'
  action:
    - service: notify.html5_notifier
      data:
        title: Alarm
        message: The alarm was triggered
    - service: tts.google_say
      data:
        message: Allarme attivato, notifica inviata.
        language: "it"
