- alias: Set At Home Automatically
  trigger:
    - platform: state
      entity_id: device_tracker.eliseo
      to: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.at_home

- alias: Set At Home Off Automatically
  trigger:
    - platform: state
      entity_id: device_tracker.eliseo
      from: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.at_home

- alias: Back Home Message
  trigger:
    - platform: state
      entity_id: switch.at_home
      to: 'on'
  action:
    - service: tts.google_say
      data_template:
        message: >
          {{ [
            "Welcome home!",
            "Nice to see you!",
            "Hello!",
            "Yo, What's up?",
            "Hey!",
            "How's going?"
          ] | random }} 
    - service: media_player.select_source
      data_template:
        entity_id: media_player.spotify
        source: "Bedroom"
    - service: media_player.shuffle_set
      data_template:
        entity_id: media_player.spotify
        shuffle: true
    - service: media_player.play_media
      data_template:
        entity_id: media_player.spotify
        media_content_id: "spotify:user:spotify:playlist:37i9dQZF1DWXmlLSKkfdAk"
        media_content_type: "playlist"
