- alias: Bedroom Movie Mode Announcement
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_movie_mode
    to: 'on'
  action: 
    service: tts.google_say
    entity_id: media_player.bedroom
    data: 
      message: "Movie Mode Enabled"
