- alias: Bedroom Movie Mode Announcement
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_movie_mode
    to: 'on'
  action: 
    service: tts.google_say
    entity_id: media_player.bedroom
    data: 
      message: "Movie Mode Enabled"

- alias: Lights off With Kodi
  trigger:
    platform: state
    entity_id: media_player.kodi_mac_mini
    from: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_movie_mode
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.bedroom_light
      - switch.bedside_lamp
      - switch.desk_lamp

- alias: Lights on With Kodi
  trigger:
    platform: state
    entity_id: media_player.kodi_mac_mini
    to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_movie_mode
      state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.bedside_lamp
      - switch.desk_lamp
