- alias: Vacation Turn Off Modes
  trigger:
    - platform: state
      entity_id: switch.vacation
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.at_home

- alias: No Home or away when in vacation
  trigger:
    - platform: state
      entity_id: switch.at_home
      to: 'on'
  condition:
    - condition: state
      entity_id: 'switch.vacation'
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.at_home
