- alias: Wake Up Lights 10min before
  trigger:
          platform: template
          value_template: '{{ (((states("sensor.next_google_home_alarm") | int) - 10*60) | timestamp_custom("%H:%M, %Y-%m-%d", true)) == states.sensor.time__date.state }}'
  action:
          service: homeassistant.turn_on
          entity_id:
                - switch.bedroom_desk_light

- alias: Wake Up Lights 5min before
  trigger:
          platform: template
          value_template: '{{ (((states("sensor.next_google_home_alarm") | int) - 5*60) | timestamp_custom("%H:%M, %Y-%m-%d", true))  == states.sensor.time__date.state }}'
  action:
          service: homeassistant.turn_on
          entity_id:
                - switch.bedroom_bedside_light

- alias: Wake Up Lights 
  trigger:
          platform: template
          value_template: '{{ ((states("sensor.next_google_home_alarm") | int) | timestamp_custom("%H:%M, %Y-%m-%d", true))  == states.sensor.time__date.state }}'
  action:
          service: homeassistant.turn_on
          entity_id:
                - switch.bedroom_ceiling_light

