alias: Bedroom Turn Off Bedside
trigger:
  - platform: state
    entity_id: light.bedroom_bedside
    to: 'on'
    for:
      minutes: 15
action:
  - service: homeassistant.turn_off
    entity_id:
      - light.bedroom_bedside

