---
id: 75A78B82-60DE-4C46-BBC0-098283B747F2
alias: Bedroom Movie Lights
description: Manages the lights when watching a movie.
trigger:
  - platform: state
    entity_id: media_player.bedroom_tv
    to: playing
  - platform: state
    entity_id: media_player.bedroom_tv
    from: playing
condition:
  - condition: state
    entity_id: input_boolean.bedroom_movie_lights
    state: 'on'
action:
  - service_template: >
      {{- "switch.turn_off" if trigger.to_state.state in "playing" else "switch.turn_on" }}
    entity_id: switch.circadian_lighting_bedroom

  - service: script.turn_on
    data_template:
      entity_id: >
        {%- if trigger.to_state.state in "playing" %}
          script.bedroom_create_snapshot
        {%- else %}
          script.bedroom_apply_snapshot
        {%- endif %}
  - service: scene.turn_on
    data_template:
      entity_id: >
        {{- "scene.bedroom_cinema_mode" if trigger.to_state.state in "playing" else "scene.dummy" }}