alias: Bedroom WakeUp 5min before
trigger:
        platform: template
        value_template: '{{ (((states("sensor.next_google_home_alarm") | int) - 5*60) | timestamp_custom("%H:%M, %Y-%m-%d", true))  == states.sensor.time__date.state }}'
action:
        service: homeassistant.turn_on
        entity_id:
        - switch.bedroom_bedside_light
