##
# Configuration
##
- platform: mqtt
  name: Movie
  command_topic: home/bedroom/configuration/movie
  state_topic: home/bedroom/configuration/movie
  icon: mdi:filmstrip
  retain: true
- platform: mqtt
  name: Music Lights
  command_topic: home/bedroom/configuration/music_lights
  state_topic: home/bedroom/configuration/music_lights
  icon: mdi:filmstrip
  retain: true


##
# LIGHTS
##
- platform: mqtt
  name: Bedroom Desk Light
  command_topic: home/bedroom/switch/desk
  state_topic: home/bedroom/switch/desk
  retain: true
- platform: mqtt
  name: Bedroom Bedside Light
  retain: true
  command_topic: home/bedroom/switch/bedside
  state_topic: home/bedroom/switch/bedside
- platform: mqtt
  retain: true
  name: Bedroom Ceiling Light
  command_topic: home/bedroom/switch/ceiling
  state_topic: home/bedroom/switch/ceiling
- platform: mqtt
  name: Bedroom Plug
  retain: true
  command_topic: home/bedroom/switch/plug
  state_topic: home/bedroom/switch/plug
