alias: Bedroom Movie Lights Deactivate
trigger:
  - platform: state
    entity_id: media_player.bedroom_tv
    from: playing
condition:
  - condition: state
    entity_id: input_boolean.bedroom_movie_lights
    state: 'on'
action:

  - service: scene.turn_on
    data:
      entity_id: "scene.bedroom_snapshot"
