id: 8BA8B16D-762A-4586-98FB-9E0262B9FA65
alias: Other Netflix Decrement Counter
trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      chat_id: !secret netflix_telegram_chat_id
condition:
  - condition: template
    value_template: >
      {{ "/dec" in trigger.event.data.command }}
action:
  - service: counter.decrement
    data_template:
      entity_id: >
        counter.other_netflix_user_{{ trigger.event.data.command | replace("/dec", "") }}
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      title: '*Message edit*'
      message: >
        ⚠️ Status:  

        {{ states.counter.other_netflix_user_0.name }}: € {{ states.counter.other_netflix_user_0.state }}  

        {{ states.counter.other_netflix_user_1.name }}: € {{ states.counter.other_netflix_user_1.state }}  
        
        {{ states.counter.other_netflix_user_2.name }}: € {{ states.counter.other_netflix_user_2.state }}
      inline_keyboard: 
          - "User0:/dec0"
          - "User1:/dec1"
          - "User2:/dec2"