##
# Temperature Sensor for the bedroom
##
- platform: mqtt
  name: Bedroom Temperature
  device_class: humidity
  state_topic: home/bedroom/sensor/dht_temperature/state
  unit_of_measurement: "°C"

##
# Humidity Sensor for the bedroom
##
- platform: mqtt
  name: Bedroom Humidity
  device_class: humidity
  state_topic: home/bedroom/sensor/dht_humidity/state
  unit_of_measurement: "%"

##
# Rest sensor to get the next alarm from the Google Home
## 
- platform: rest
  resource: http://192.168.0.12:8008/setup/assistant/alarms
  name: Next Google Home Alarm
  value_template: >
          {% set minimumtime=value_json.alarm[0]["fire_time"] %}
          {% for alarm in value_json.alarm %}
                {% if alarm["fire_time"] < minimumtime %}
                        {% set minimumtime=alarm["fire_time"] %}
                {% endif %}
          {% endfor %}
          {{ ((minimumtime | int)/1000) }}

##
# Sensor to get the status of the Epson printer
##
- platform: command_line
  command: curl http://192.168.0.13/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Black Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.0.13/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Yellow Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.0.13/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Magenta Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.0.13/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Cyan Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.0.13/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk '/message_id/' | grep -oP '(?<=ride;'\''>).*(?=<\/div>)' | sed 's/&nbsp;/\ /g' | sed 's/.\///g'
  name: Epson XP-205 Status
