- platform: command_line
  command: curl http://192.168.1.77/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Black Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.1.77/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Yellow Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.1.77/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Magenta Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.1.77/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  name: Epson XP-205 Cyan Ink
  unit_of_measurement: '%'
- platform: command_line
  command: curl http://192.168.1.77/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk '/message_id/' | grep -oP '(?<=ride;'\''>).*(?=<\/div>)' | sed 's/&nbsp;/\ /g' | sed 's/.\///g'
  name: Epson XP-205 Status
