##
# Template sensor for getting the various shifts of cleaning
##
- platform: template
  sensors:
    clean_shift_eliseo:
      friendly_name: "Eliseo Cleaning Shift"
      icon_template: mdi:broom
      value_template: >
        {{ states.calendar.house_cleaning.attributes.description.split('  \n')[0] }}
    clean_shift_daniele:
      friendly_name: "Daniele Cleaning Shift"
      icon_template: mdi:broom
      value_template: >
        {{ states.calendar.house_cleaning.attributes.description.split('  \n')[1] }}
    clean_shift_lorenzo:
      friendly_name: "Lorenzo Cleaning Shift"
      icon_template: mdi:broom
      value_template: >
        {{ states.calendar.house_cleaning.attributes.description.split('  \n')[2] }}
    who_cleans:
      friendly_name: "Who Cleans?"
      icon_template: mdi:broom
      value_template: >
        {{ states.calendar.house_cleaning.attributes.description }}
##
# Speedtest Sensor
##
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
