##
# Time & Date Sensor
##
- platform: time_date
  display_options:
    - 'time_date'

##
# Sensor used to get the mean value of the air quality
##
- platform: min_max
  entity_ids:
    - sensor.waqi_grande_torino_leini_piemonte_italy
    - sensor.waqi_lingotto_torino_piemonte_italy
    - sensor.waqi_rebaudengo_torino_piemonte_italy
    - sensor.waqi_rubino_torino_piemonte_italy
  name: Air Quality
  type: mean
  round_digits: 0
