alias: Bedroom WakeUp 10min before
trigger:
        platform: template
        value_template: '{{ (((states("sensor.next_google_home_alarm") | int) - 10*60) | timestamp_custom("%H:%M, %Y-%m-%d", true)) == states.sensor.time__date.state }}'
action:
        service: homeassistant.turn_on
        entity_id:
              - switch.bedroom_desk_light