alias: Alarm Away
trigger:
  - platform: state
    entity_id: group.away_sensors
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.test_alarm
    state: armed_away
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.test_alarm
