- platform: mqtt_json
  name: Bed Light Strip
  state_topic: "home/bedroom/light/under_bed"
  command_topic: "home/bedroom/lights/under_bed"
  brightness: true
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash]
  optimistic: false
  qos: 0
