# lovelace_gen

- title: Settings
  icon: mdi:settings
  path: settings
  cards:
    - !include 
      - ../includes/header.yaml
      - title: "Settings"

    - type: vertical-stack
      cards:
        - !include 
          - ../includes/section.yaml
          - title: "Transmission"
        - type: horizontal-stack
          cards:

            - type: custom:decluttering-card
              template: mini_graph
              variables:
                - entity_id: sensor.transmission_up_speed
                - color: purple
                - name: Upload

            - type: custom:decluttering-card
              template: mini_graph
              variables:
                - entity_id: sensor.transmission_down_speed
                - color: red
                - name: Download

        - type: entities
          entities:
            - entity: switch.transmission_switch
              name: Enable
            - entity: sensor.transmission_status
              name: Status
    - !include 
          - ../includes/section.yaml
          - title: "Transportation"
    - type: entities
      entities:
        - sensor.city_next_tram

    - !include 
      - ../includes/section.yaml
      - title: "Automations"
    - type: custom:auto-entities
      card:
        type: entities
      filter:
        include:
          - entity_id: automation.*

    - !include 
      - ../includes/section.yaml
      - title: "Printer"
    - type: custom:auto-entities
      card:
        type: entities
      filter:
        include:
          - entity_id: sensor.bedroom_printer_*

    - !include 
      - ../includes/section.yaml
      - title: "More"
    - type: entities
      entities:
        - input_select.system_day_state

    - !include 
      - ../includes/section.yaml
      - title: "Addons"

    - type: custom:mod-card
      style: |
        ha-card {
          margin: -8px;
        }
      card:
        type: custom:layout-card
        layout: horizontal
        column_width: 50%
        justify_content: start
        cards:
          - type: custom:decluttering-card
            template: "hk_link"
            variables:
              - path: zigbee2mqtt
              - name: Zigbee
              - icon: mdi:zigbee