esphome:
  name: kitchen_sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

sensor:
  - platform: dht
    pin: GPIO02
    model: DHT11
    update_interval: 15s
    temperature:
      name: "Kitchen Temperature"
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 1   

    humidity:
      name: "Kitchen Humidity"
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 1   
 
  - platform: wifi_signal
    name: kitchen_sensor_wifi_signal
    update_interval: 10s