---
id: 4FBB8851-AEF3-4BBE-88F4-2A083FA13AF0
alias: House Lights Off When Away
description: Turns off the lights when I'm not at home.
trigger:
  - platform: state
    entity_id:
      - person.eliseo_martelli
    from: "home"
action:
  - service: light.turn_off
    entity_id: all
  - service: switch.turn_off
    entity_id: all
